name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.APP_PATH }}
          git pull origin main

          sed "s/__DOMAIN__/${{ secrets.DOMAIN }}/g" default.conf > default.conf

          docker compose down
          docker compose up --build -d